### ISSUE TITLE
Broken generated Dockerfile using 0.0.8

### ISSUE THREAD

**Issue by lebris** [Niktux/whalephant#9]
`whalephant.yml` (Working using `0.7.0`)
```
name: onyx-skeleton
php:
    version: 7.1
extensions:
    - xdebug
ini:
    - "error_reporting = E_ALL;"
    - "xdebug.var_display_max_depth = 5;"
```

The generated `Dockerfile`
```
FROM php:7.1-cliRUN pecl install xdebug 

RUN docker-php-ext-enable xdebug 

WORKDIR /var/www/onyx-skeleton

COPY php.ini /usr/local/etc/php/conf.d
```

So docker is yelling 
```
Error response from daemon: Dockerfile parse error line 1: FROM requires either one or three arguments
```

The mistake seems to come from the hyphen on this line https://github.com/Niktux/whalephant/blob/80a35cdca2fea102b2e9abb3240be1544adc2cc0/views/layout.twig#L3

The hyphen tells twig to trim **all** whitespaces (including new lines) until the next non-whitespace character.

- https://twig.symfony.com/doc/2.x/templates.html#whitespace-control

**Comment by Niktux** [comment]
Cannot reproduce in 0.9.0

whalephant.yml :
```yml
name: issue-9
php:
    version: 7.1
extensions:
    - xdebug
ini:
    - "error_reporting = E_ALL;"
    - "xdebug.var_display_max_depth = 5;"
```

Generated Dockerfile :
```Dockerfile
FROM php:7.1-cli
RUN pecl install xdebug 

RUN docker-php-ext-enable xdebug 

WORKDIR /var/www/issue-9

COPY php.ini /usr/local/etc/php/conf.d

```

0.9.0 is coming from pecl extension handling refactor. The bug was fixed during refactor
